### ISSUE TITLE
Undefined array key 1

### ISSUE THREAD

**Issue by amirmashmul** [4xmen/xshop#19]
وقتی لگو سایت رو عوض میکنم با این ارور روبرو میشم   
Undefined array key 1

 public function thumbUrl()
    {

        if ($this->getMedia()->count() > 0) {

            return $this->getMedia()[$this->image_index]->getUrl('product-thumb');

        } else {

            return asset('/images/logo.png');

        }

    }

**Comment by A1Gard** [comment]
این ارور ارتباطی با logo سایت ندارد!

یکی از محصولات عکس index انتخاب شده و حذف شده است

در هر صورت محصولات رو آپدیت کنید یا دستور
`php artisan migrate:fresh --seed`
رو بزنید تا محصولات آپدیت شن
 اگر برطرف نشد جزئیات بیشتری بدید

**Comment by amirmashmul** [comment]
> این ارور ارتباطی با logo سایت ندارد!
> 
> یکی از محصولات عکس index انتخاب شده و حذف شده است
> 
> در هر صورت محصولات رو آپدیت کنید یا دستور `php artisan migrate:fresh --seed` رو بزنید تا محصولات آپدیت شن اگر برطرف نشد جزئیات بیشتری بدید

**Comment by amirmashmul** [comment]
خیلی ممنون ، حل شد فقط اگر بخواهم تو هاست اطلاعات رو اپلود کنم باید چه مراحلی رو پیش ببرم؟

**Comment by A1Gard** [comment]
محصول عکس نداشته باشه لوگو رو نشون میده عکس داشته باشه عکس محصول رو نشون میده

**Comment by amirmashmul** [comment]
عکس برای محصول گذاشتم ولی همچنان عکس logo   رو نمایش میده

**Comment by A1Gard** [comment]
یه خروجی json از محصولت بده لطفا اینو تو web.php اضافه کن و آی دی محصولت رو جایگزین ۱ کن 
```
Route::get('/test',function (){
   $p = \App\Models\Product::whereId(2)->first();
   $m = $p->getMedia();
   return [$p,$m];
});
```

بعدش `http://127.0.0.1:8000/test` باز کن نتیجه رو بفرست

**Comment by amirmashmul** [comment]
دقیقا متوجه نشدم و فایل web.php  رو پیدا نکردم

**Comment by amirmashmul** [comment]
فایل index اصلی تو کدوم دایرکتوریه که بخوام تغییراتی رو سایت انجام بدم

**Comment by A1Gard** [comment]
سوالات در بخش  discussions مطرح کنید:
 
 https://github.com/4xmen/xshop/discussions
 
 برای مشکلات issue باز کنید ، برای هر سوال و مشکل یه یک موضوع جدید باز کنید که سایر کاربران هم بتونند دسترسی داشته باشند
