### ISSUE TITLE
فایل INDEX  اصلی برای تغییرات در پروژه

### ISSUE THREAD

**Issue by amirmashmul** [4xmen/xshop#20]
فایل INDEX  اصلیو نمیتونم پیدا کنم که به صورت استاتیک تغییراتی بدهم به علاوه فایل جاوا اسکریت برای تغییرات اسلایدر

**Comment by A1Gard** [comment]
پیشنهاد می‌کنم پیش از ایجاد تغییرات در xshop کمی لاراول یاد بگیرید

https://github.com/4xmen/xshop/blob/main/resources/views/website/index.blade.php
