### ISSUE TITLE
Please make an english translation too.

### ISSUE THREAD

**Issue by msamgan** [4xmen/xshop#24]
The product looks good. Please build an English translation of the same.

**Comment by A1Gard** [comment]
That's really kind of you bro

The base of system is English, you need just change lang on config:

https://github.com/4xmen/xshop/blob/main/config/app.php#L95

and for fake date:

https://github.com/4xmen/xshop/blob/main/config/app.php#L121

Otherwise if you problem with rtl and ltr make new isuee
