### ISSUE TITLE
کانفیگ پنل پیامکی

### ISSUE THREAD

**Issue by matinrajabi** [4xmen/xshop#31]
سلام بخش sendsms رو چطور کانفیگ کنیم برای پنل پیامکی؟

**Comment by SadeghPM** [comment]
ارسال پیامک بر روی سرویس زیر انجام گرفته:
http://payamak-panel.com
در فایل کانفیگ app مقادیر یوزر و پسورد رو قرار بدید.

**Comment by matinrajabi** [comment]
ممنون از پاسخگویی
فقط این لینک ریدایرکت میشه داخل صفحه لاگین من از کجا داخل این سرویس ثبت نام کنم؟ چون با این سرویس اصلا اشنایی نداشتم تا الان.

**Comment by matinrajabi** [comment]
ممنون از پاسخگویی
فقط این لینک ریدایرکت میشه داخل صفحه لاگین من از کجا داخل این سرویس ثبت نام کنم؟ چون با این سرویس اصلا اشنایی نداشتم تا الان.

**Comment by A1Gard** [comment]
میتونید از فرا پیامک هم سرویس بگیرید، و در `.env` ست کنید فراموش نکنید که SIGNUP_SMS هم true باشد وگرنه با ایمیل کاربران ثبت نام می‌کنند
