### ISSUE TITLE
update setting seeder or  fix bug

### ISSUE THREAD

**Issue by A1Gard** [4xmen/xshop#34]
We need fix setting seeder for english is good idea and we have some problem for multi lang here:

https://github.com/4xmen/xshop/blob/main/database/seeders/SettingSeeder.php

![image](https://github.com/4xmen/xshop/assets/9222481/3fe24ecb-b830-4761-a23e-5fa9ccd9ef58)

**Comment by YasinDehfuli** [comment]
All Setting Parts and JSON fields were Translated into English.
