### ISSUE TITLE
bug: translate large translate file by ai  API

### ISSUE THREAD

**Issue by A1Gard** [4xmen/xshop#35]
we have problem with AI translate large json file api here:

dashboard/langs/translates

![image](https://github.com/4xmen/xshop/assets/9222481/ced5d766-04fb-46b7-a039-ff1a367d3225)

We need to find solution!

**Comment by farzady** [comment]
Could you send me json file to check it?

**Comment by A1Gard** [comment]
Here you are dude:

https://github.com/4xmen/xshop/blob/main/resources/lang/fr.json
