### ISSUE TITLE
مشکل در استفاده از installer با لاراگون

### ISSUE THREAD

**Issue by rezaexe21** [4xmen/xshop#38]
سلام سال نو مبارک
بنده روی لوکال هاست لاراگون نصبش کردم  
ولی فقط فایل ها را نشون میده میشه راهنمایی بفرمایید
و این که در آدرس installer/installer.php
خطای زیر را میدهد :
Requrirment check
PHP Version check 8.1 or Above
PHP extentions not installed: pdo_mysql, sqlite3, soap, zip, gd, mbstring, xml, json, fileinfo, bcmath,
PHP extentions not installed: curl,
Write permission!
Packages already installed
Database connection is OK!
Rewrite error:
Your server is : Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.2.17
If you use `PHP`, restart laravel
If you use `Apache`, your public_html has problem
If you use `NGINX`, active this rewrite on domain config, then restart server:
rewrite ^/(.*)$ /index.php/$1 last;

**Comment by A1Gard** [comment]
سلام وقت شما هم بخیر این مشکل برای این هستش که ورژن php شما مناسب نیست و هنوز بخش installer کامل نشده لطفا طبق راهنمایی پارسی برای نصب پیش برید مشکل داشتید بفرمایید حلش کنیم!

نکته: ظاهرا چند تا مشکل دارید:

- روی php شما curl نصب نیست برای درگاه های بانکی ضروری هستش
- اسکریپت توانایی نوشتن روی فایل های مورد نظر رو نداره
- 
اما اگر می‌خواید کمک کنید installer رو تکمیل کنیم یه بفرمایید هماهنگ بشیم!
