### ISSUE TITLE
کمک برای راه اندازی این برنامه برای مصارف تجاری

### ISSUE THREAD

**Issue by Amir2x4** [4xmen/xshop#39]
با سلام لطفا یه راهنمایی بکنید که اگه بخواییم این برنامه رو بعنوان یه ساین فروشگاهی استفاده کنیم باید چیکار کنیم
منظورم پشتیبانی و هزینه هاش هست
با تشکر

**Comment by Amir2x4** [comment]
البته دیتابیس میخوام sqlserver باشه خودم بصورت لوکال تست کردم مجبور شدم دیتابیس رو دستی ایجاد کنم و درایور های sql pdo رو نصب کردم درست کار کرد

**Comment by A1Gard** [comment]
از نظر تجاری مشکلی نداره، الان ران هستش رو ساایت های زیادی، ولی با mysql , sqlite امتحانشو پس داده، خوشحال میشم تجربه‌اتون رو در مورد ms sql server هم به اشتراک بذارید سیستم رو بهینه تر کتیم.
