### ISSUE TITLE
issue in migrations file

### ISSUE THREAD

**Issue by Bdiwy** [4xmen/xshop#41]
i have a problem when run `php artisan migrate` in files 

1. 2024_05_07_130324_create_props_table  **in line** : `$table->text('unit')->nullable()->default(' ');`
2.  2024_07_04_053952_create_parts_table.php  **in line** : `$table->json('data')->default('[]');`

i solve it by making them `->nullable()` is right for your system or there is a better solution .

**Comment by A1Gard** [comment]
You are using mysql or maria db?

**Comment by Bdiwy** [comment]
mysql

**Comment by A1Gard** [comment]
You can choose mariadb or change json fields to blob

**Comment by Bdiwy** [comment]
yes I already did this
