### ISSUE TITLE
مراحل نصب

### ISSUE THREAD

**Issue by mmdreza2003** [4xmen/xshop#42]
سلام لطفا مراحل نصب رو بزارید صفر تا صد که بتونیم پروژه رو اجرا کنیم ممنون

**Comment by A1Gard** [comment]
سلام پروژه در حال ریفکتور هستش، می‌تونین ورژن ۱ رو از رو دانلود کنید تو مراحل نصب هستش:


https://github.com/4xmen/xshop/releases

یا من ریپوی نسخه ۱ رو آرشیو کردم

https://github.com/A1Gard/xshop.v1

رید می فارسی هم داره و اما یه اسکرین شات از ورژن  جدید هم بدم:

![image](https://github.com/user-attachments/assets/30b67a70-e7d6-4a75-8b3f-460a800b27b9)

**Comment by mmdreza2003** [comment]
ممنونم موفق باشید.
