### ISSUE TITLE
question about using weblog features 

### ISSUE THREAD

**Issue by dev-am1** [4xmen/xshop#7]
hello and thank you for this awesome project, 
I want to add weblog posts in index page right next to products,
the issue I'm having is,
the posts I made are being shown in about us page without capability of opening or having a separate page representing that post, 
can you guide me through the process of achieving this goal ? many thanks in advance, 
دم شما گرم.

**Comment by A1Gard** [comment]
Hello bro, thanks for your kindness.
Yes it's completely possible, what's the solution:

Class `WebsiteController` function  `index` handle the index of website you can these line to  function:

$posts = Post:orderBy('id','desc')->limit(5)->get();
return view('website.index', compact('cats', 'sliders', 'vid','posts')); // add posts to compacts

https://github.com/4xmen/xshop/blob/main/app/Http/Controllers/WebsiteController.php#LL67C9-L67C73

Then add your blade to https://github.com/4xmen/xshop/blob/main/resources/views/website/index.blade.php#LL162C15-L162C15

If you have problem to find resources you can visit `127.0.0.1:8000/posts` to see all posts or https://github.com/4xmen/xshop/blob/main/resources/views/website/posts.blade.php

BTW don't for get make post status published.

Kind regards, A1Gard

**Comment by farzady** [comment]
If you wanna we add this feature to project just post new issue, my team adding that soon :)
